### ISSUE TITLE
@supports not working on iOS 9.3.2?

### ISSUE THREAD

**Issue by ErikVeland** [Hiswe/vh-check#1]
My test case isn't calculating?

`min-height: calc(98vh);@supports (height: var(--vh-offset)) {min-height: calc(98vh - var(--vh-offset));background: red;};`

(@supports and its styles are crossed out in the Web Inspector. (background:red is for debugging)).

**Comment by ErikVeland** [comment]
If I remove the @supports it still doesn't calculate the offset. It definitely has 

`<style>​:root { --vh-offset: 69px; }​</style>​`

in the DOM.

**Comment by ErikVeland** [comment]
Strangely it works if I removed the first declaration of min-height. If only I could get this to work with @supports now it would be perfect :/

**Comment by Hiswe** [comment]
@ErikVeland I think It's because my example use a CSS pre-processor…

The code should be:

``` css
main {
  /* for browser supporting VH without buggy behaviour & no supporting of CSS var */
  min-height: calc(100vh);
}
/* make sure that CSS var are supported */
/* buggyFill will work on iOS 9.3+ only */
/* will degrade on a buggy 100vh on older version of iOS */
@supports (height: var(--vh-offset)) {
  main {
    min-height: calc(100vh - var(--vh-offset));
  }
}
```

I'll fix that ^^
